#theme: jekyll-theme-architect
#theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs
#theme: jekyll-theme-dinky
#theme: jekyll-theme-hacker
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-merlot
#theme: jekyll-theme-midnight
#theme: minima
#theme: jekyll-theme-modernist
#theme: jekyll-theme-slate
#theme: jekyll-theme-tactile
#theme: jekyll-theme-time-machine
title: GDS projects
description: from nothing...
logo: cmap2.png
markdown: kramdown
